# -*- coding: utf-8 -*-
"""Buscaprimos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZC5aokVJpoo7kOBcWkQ0dAFRozX5ZQ87
"""

while True:
    try:
        n = int(input("Ingrese un número límite (mayor que 1): "))
        if n <= 1:
            print("El número límite debe ser mayor que 1. Inténtelo de nuevo.")
        else:
            break
    except ValueError:
        print("Debe ingresar un número entero. Inténtelo de nuevo.")

primos = []
for i in range(2, n+1):
    es_primo = True
    for j in range(2, i):
        if i % j == 0:
            es_primo = False
            break
    if es_primo:
        primos.append(i)
print("Los números primos hasta", n, "son:", primos)

